spring:
  application:
    name: LostAndFoundBackground
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PWD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PWD}
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s

mybatis:
  configuration:
    map-underscore-to-camel-case: true

  mapper-locations: classpath:mapper/*.xml

jasypt:
  encryptor:
    #从环境变量中获取
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}

